---
development:
  cloud_name: hassan0140
  api_key: '212213456584239'
  api_secret: HL_tsS3dL698cmN57HiQ8D3XnXs
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: hassan0140
  api_key: '212213456584239'
  api_secret: HL_tsS3dL698cmN57HiQ8D3XnXs
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: hassan0140
  api_key: '212213456584239'
  api_secret: HL_tsS3dL698cmN57HiQ8D3XnXs
  enhance_image_tag: true
  static_file_support: false
