# frozen_string_literal: true

# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
@default_password = '123456'
User.create([{ user_name: 'Hassan Raza', email: 'hassanraza0140@gmail.com', user_role: 'admin',
               password: 'Hassan' },
             { user_name: 'Hassan', email: 'hassan.raza@devsinc.com', user_role: 'BD',
               password: @default_password },
             { user_name: 'Test User 1', email: 'testuser1@gmail.com', user_role: 'BD',
               password: @default_password },
             { user_name: 'Noah Ryan', email: '2noahryan@gmail.com', user_role: 'TM',
               password: @default_password },
             { user_name: 'Test User 2', email: 'testuser2@gmail.com', user_role: 'Tm',
               password: @default_password },
             { user_name: 'Test User 3', email: 'testuser3@gmail.com', user_role: 'TM',
               password: @default_password },
             { user_name: 'Test User 4', email: 'testuser4@gmail.com', user_role: 'TM',
               password: @default_password },
             { user_name: 'Test User 5', email: 'testuser5@gmail.com', user_role: 'TM',
               password: @default_password },
             { user_name: 'Test User 6', email: 'testuser6@gmail.com', user_role: 'engineer',
               password: @default_password },
             { user_name: 'Test User 7', email: 'testuser7@gmail.com', user_role: 'engineer',
               password: @default_password },
             { user_name: 'Test User 8', email: 'testuser8@gmail.com', user_role: 'engineer',
               password: @default_password },
             { user_name: 'Test User 9', email: 'testuser9@gmail.com', user_role: 'engineer',
               password: @default_password },
             { user_name: 'Test User 10', email: 'testuser10@gmail.com', user_role: 'engineer',
               password: @default_password },
             { user_name: 'Test User 11', email: 'testuser11@gmail.com', user_role: 'engineer',
               password: @default_password },
             { user_name: 'Test User 12', email: 'testuser12@gmail.com', user_role: 'engineer',
               password: @default_password },
             { user_name: 'Test User 13', email: 'testuser13@gmail.com', user_role: 'engineer',
               password: @default_password },
             { user_name: 'Test User 14', email: 'testuser14@gmail.com', user_role: 'engineer',
               password: @default_password },
             { user_name: 'Test User 15', email: 'testuser15@gmail.com', user_role: 'engineer',
               password: @default_password }])

@default_client_contact = '12345678900'
Lead.create([{ lead_name: 'Test Lead 1', lead_type: 'interview', user_id: 1, client_name: 'Test Client 1',
               client_address: 'Test Address 1', client_email: 'clientemail1@gmail.com',
               client_contact: @default_client_contact },
             { lead_name: 'Test Lead 2', lead_type: 'interview', user_id: 2, client_name: 'Test Client 2',
               client_address: 'Test Address 2', client_email: 'clientemail2@gmail.com',
               client_contact: @default_client_contact },
             { lead_name: 'Test Lead 3', lead_type: 'interview', user_id: 1, client_name: 'Test Client 3',
               client_address: 'Test Address 3', client_email: 'clientemail3@gmail.com',
               client_contact: @default_client_contact },
             { lead_name: 'Test Lead 4', lead_type: 'interview', user_id: 1, client_name: 'Test Client 4',
               client_address: 'Test Address 4', client_email: 'clientemail4@gmail.com',
               client_contact: @default_client_contact },
             { lead_name: 'Test Lead 5', lead_type: 'interview', user_id: 2, client_name: 'Test Client 5',
               client_address: 'Test Address 5', client_email: 'clientemail5@gmail.com',
               client_contact: @default_client_contact },
             { lead_name: 'Test Lead 6', lead_type: 'test', user_id: 1, client_name: 'Test Client 6',
               client_address: 'Test Address 6', client_email: 'clientemail6@gmail.com',
               client_contact: @default_client_contact },
             { lead_name: 'Test Lead 7', lead_type: 'test', user_id: 2, client_name: 'Test Client 7',
               client_address: 'Test Address 7', client_email: 'clientemail7@gmail.com',
               client_contact: @default_client_contact },
             { lead_name: 'Test Lead 8', lead_type: 'test', user_id: 1, client_name: 'Test Client 8',
               client_address: 'Test Address 8', client_email: 'clientemail8@gmail.com',
               client_contact: @default_client_contact },
             { lead_name: 'Test Lead 9', lead_type: 'test', user_id: 2, client_name: 'Test Client 9',
               client_address: 'Test Address 9', client_email: 'clientemail9@gmail.com',
               client_contact: @default_client_contact }])

Phase.create([{ phase_type: 'interview', start_date: '2021-09-11', end_date: '2021-10-01', lead_id: 1, user_id: 4,
                assigned_engineer: %w[6 7 8] },
              { phase_type: 'interview', start_date: '2021-09-11', end_date: '2021-10-03', lead_id: 1, user_id: 4,
                assigned_engineer: %w[9 10 18] },
              { phase_type: 'interview', start_date: '2021-09-13', end_date: '2021-10-05', lead_id: 1, user_id: 4,
                assigned_engineer: %w[16 17 11] },
              { phase_type: 'interview', start_date: '2021-09-15', end_date: '2021-09-27', lead_id: 2, user_id: 4,
                assigned_engineer: %w[12 15] },
              { phase_type: 'interview', start_date: '2021-09-12', end_date: '2021-09-21', lead_id: 3, user_id: 5,
                assigned_engineer: %w[11 17 18] },
              { phase_type: 'interview', start_date: '2021-09-17', end_date: '2021-09-22', lead_id: 4, user_id: 6,
                assigned_engineer: %w[9 14 16] },
              { phase_type: 'interview', start_date: '2021-09-19', end_date: '2021-09-23', lead_id: 5, user_id: 5,
                assigned_engineer: ['12'] },
              { phase_type: 'interview', start_date: '2021-09-21', end_date: '2021-09-29', lead_id: 6, user_id: 7,
                assigned_engineer: %w[17 14 9] },
              { phase_type: 'interview', start_date: '2021-09-23', end_date: '2021-10-03', lead_id: 7, user_id: 8,
                assigned_engineer: %w[18 15 10] },
              { phase_type: 'interview', start_date: '2021-09-22', end_date: '2021-10-04', lead_id: 8, user_id: 5,
                assigned_engineer: %w[14 11 10] },
              { phase_type: 'interview', start_date: '2021-09-24', end_date: '2021-10-11', lead_id: 9, user_id: 8,
                assigned_engineer: %w[9 17 10] },
              { phase_type: 'interview', start_date: '2021-10-02', end_date: '2021-10-13', lead_id: 9, user_id: 4,
                assigned_engineer: %w[13 14 11] },
              { phase_type: 'test', start_date: '2021-09-14', end_date: '2021-09-23', lead_id: 1, user_id: 5,
                assigned_engineer: %w[16 17 18] },
              { phase_type: 'test', start_date: '2021-09-18', end_date: '2021-10-01', lead_id: 1, user_id: 6,
                assigned_engineer: %w[10 9] },
              { phase_type: 'test', start_date: '2021-09-23', end_date: '2021-10-05', lead_id: 2, user_id: 8,
                assigned_engineer: [] },
              { phase_type: 'test', start_date: '2021-09-25', end_date: '2021-10-07', lead_id: 3, user_id: 7,
                assigned_engineer: ['16'] },
              { phase_type: 'test', start_date: '2021-10-01', end_date: '2021-10-13', lead_id: 4, user_id: 7,
                assigned_engineer: %w[16 17 18 9 10] },
              { phase_type: 'test', start_date: '2021-10-04', end_date: '2021-10-16', lead_id: 5, user_id: 8,
                assigned_engineer: %w[11 13 15] },
              { phase_type: 'test', start_date: '2021-10-05', end_date: '2021-10-19', lead_id: 6, user_id: 4,
                assigned_engineer: %w[10 9] },
              { phase_type: 'test', start_date: '2021-09-11', end_date: '2021-10-02', lead_id: 7, user_id: 5,
                assigned_engineer: %w[15 16] }])

Comment.create([{ comment_text: 'Test Comment 1', user_id: 1, phase_id: 1 },
                { comment_text: 'Test Comment 2', user_id: 1, phase_id: 1 },
                { comment_text: 'Test Comment 3', user_id: 1, phase_id: 1 },
                { comment_text: 'Test Comment 4', user_id: 1, phase_id: 2 },
                { comment_text: 'Test Comment 5', user_id: 1, phase_id: 2 },
                { comment_text: 'Test Comment 6', user_id: 2, phase_id: 2 },
                { comment_text: 'Test Comment 7', user_id: 2, phase_id: 3 },
                { comment_text: 'Test Comment 8', user_id: 2, phase_id: 4 },
                { comment_text: 'Test Comment 9', user_id: 2, phase_id: 5 },
                { comment_text: 'Test Comment 10', user_id: 3, phase_id: 6 },
                { comment_text: 'Test Comment 11', user_id: 3, phase_id: 7 },
                { comment_text: 'Test Comment 12', user_id: 3, phase_id: 8 },
                { comment_text: 'Test Comment 13', user_id: 4, phase_id: 9 },
                { comment_text: 'Test Comment 14', user_id: 4, phase_id: 10 },
                { comment_text: 'Test Comment 15', user_id: 4, phase_id: 11 },
                { comment_text: 'Test Comment 16', user_id: 4, phase_id: 12 },
                { comment_text: 'Test Comment 17', user_id: 5, phase_id: 13 },
                { comment_text: 'Test Comment 18', user_id: 6, phase_id: 14 },
                { comment_text: 'Test Comment 19', user_id: 7, phase_id: 15 },
                { comment_text: 'Test Comment 20', user_id: 8, phase_id: 16 },
                { comment_text: 'Test Comment 21', user_id: 9, phase_id: 17 },
                { comment_text: 'Test Comment 22', user_id: 10, phase_id: 18 },
                { comment_text: 'Test Comment 23', user_id: 11, phase_id: 18 },
                { comment_text: 'Test Comment 24', user_id: 12, phase_id: 19 },
                { comment_text: 'Test Comment 25', user_id: 13, phase_id: 19 },
                { comment_text: 'Test Comment 26', user_id: 14, phase_id: 19 },
                { comment_text: 'Test Comment 27', user_id: 15, phase_id: 20 },
                { comment_text: 'Test Comment 28', user_id: 16, phase_id: 20 },
                { comment_text: 'Test Comment 29', user_id: 17, phase_id: 3 },
                { comment_text: 'Test Comment 30', user_id: 18, phase_id: 9 }])
